<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>CV Database</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap-theme.min.css">
    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->    
  </head>
  <body>

    <div class="container">
      <div class="panel panel-default">
        <div class="panel-heading clearfix">
          <h4 class="pull-left">Skill Database</h4>
          <a href="<?php echo $data['router']->pathFor('index'); ?>" class="pull-right btn btn-primary btn">Home</a>
        </div>
      </div> 
            
      <div class="row">
        <div class="col-sm-6 panel">
          <div class="panel-heading">Add a new CV to the database.</div>
          <div class="btn-group btn-group-justified">
            <a role="button" class="btn btn-primary" href="<?php echo $data['router']->pathFor('add'); ?>">Add</a>
          </div>
        </div>
        
        <div class="col-sm-6 panel">
          <div class="panel-heading">Search the database.</div>
          <div class="btn-group btn-group-justified">
            <a role="button" class="btn btn-primary" href="<?php echo $data['router']->pathFor('search'); ?>">Search</a>
          </div>
        </div>
      </div>
    </div>
      
    <div class="container">
      <p class="text-center">
        <a href="<?php echo $data['router']->pathFor('legal'); ?>" role="button" class="btn btn-default btn-sm">Legal</a>
      </p>
    </div> 
    
  </body>
</html>