<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>CV Database</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap-theme.min.css">
    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
    <style type="text/css">
    em {
      background-color: yellow;
      font-style: normal;
    }
    </style>
  </head>
  <body>

    <div class="container">
      <div class="panel panel-default">
        <div class="panel-heading clearfix">
          <h4 class="pull-left">Search CVs</h4>
          <div class="btn-group pull-right">
            <a role="button" class="btn btn-primary" href="<?php echo $data['router']->pathFor('add'); ?>">Add</a>
          </div>
        </div>
      </div>  
      
      <div>   
        <form method="get" action="<?php echo $data['router']->pathFor('search'); ?>">
          <div class="form-group">
            <input type="text" name="q" value="<?php echo isset($data['q']) ? $data['q'] : ''; ?>" class="form-control" placeholder="Search for...">
          </div>
          <div class="form-group">
            <button type="submit" name="submit" class="btn btn-primary">Search</button>
          </div>          
        </form>
      </div>

      <div>
      <?php if (isset($data['hits']) && count($data['hits'])): ?>
        <h4>Search Results</h4>
        <ul class="list-group row clearfix">
        <?php foreach ($data['hits'] as $doc): ?>
          <li class="list-group-item clearfix">
            <strong><?php echo $doc['_source']['name']; ?></strong>
            <div class="btn-group pull-right">
              <a href="<?php echo $data['router']->pathFor('download', array('id' => $doc['_id'])); ?>" role="button" class="btn-sm btn-success">Download CV</a> 
              <a href="mailto:<?php echo $doc['_source']['email']; ?>" role="button" class="btn-sm btn-success">Email</a> 
              <?php if (!empty($doc['_source']['url'])): ?>
              <a href="<?php echo $doc['_source']['url']; ?>" role="button" class="btn-sm btn-success">Connect</a> 
              <?php endif; ?>
            </div>
            <br />
            <?php echo (isset($doc['highlight']['content'][0])) ? '... ' . $doc['highlight']['content'][0] . ' ... <i>(in content)</i><br/>' : ''; ?> 
            <?php echo (isset($doc['highlight']['notes'][0])) ? ' ... ' . $doc['highlight']['notes'][0] . ' ... <i>(in notes)</i>' : ''; ?>
          </li>
        <?php endforeach; ?>
        </ul>
      <?php endif; ?>
      </div> 
    </div>
      
    <div class="container">
      <p class="text-center">
        <a href="<?php echo $data['router']->pathFor('legal'); ?>" role="button" class="btn btn-default btn-sm">Legal</a>
      </p>
    </div> 
    
  </body>
</html>